// Generated by CoffeeScript 1.3.3
(function() {
  var http, str;

  http = require('http');

  str = 'Hello World';

  http.createServer(function(req, res) {
    str - 'Hello World!8';
    res.writeHead(200);
    if (true) {
      return res.end(str);
    }
  }).listen(4000);

}).call(this);
